
# following command can be used to generate this yaml file:
# kubectl create secret docker-registry harbor-secret -n itcp-integration --docker-username=itcpdevops --docker-password=Deployment2itcp --docker-email=itcpdevops@itcp.com --docker-server=harbor.itcpdev.mrr.ste.com --dry-run=client -o yaml > harbor-secret.yaml

apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJoYXJib3IuaXRjcGRldi5tcnIuc3RlLmNvbSI6eyJ1c2VybmFtZSI6Iml0Y3BkZXZvcHMiLCJwYXNzd29yZCI6IkRlcGxveW1lbnQyaXRjcCIsImVtYWlsIjoiaXRjcGRldm9wc0BpdGNwLmNvbSIsImF1dGgiOiJhWFJqY0dSbGRtOXdjenBFWlhCc2IzbHRaVzUwTW1sMFkzQT0ifX19
kind: Secret
metadata:
  creationTimestamp: null
  name: harbor-secret
  namespace: demo
type: kubernetes.io/dockerconfigjson
